USE [FaculdadeTISelvagem]
GO

/****** Object:  Table [dbo].[Aluno]    Script Date: 16/07/2013 17:05:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Aluno](
	[AlunoId] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](75) NULL,
	[Mae] [varchar](75) NULL,
	[DataNascimento] [date] NULL,
 CONSTRAINT [PK_Aluno] PRIMARY KEY CLUSTERED 
(
	[AlunoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


